server:
  port: 8888
  servlet:
    session:
      timeout: 10m
      cookie:
        path: /
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/act?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    type:  com.alibaba.druid.pool.DruidDataSource
  redis:
#    host: yuyoyo.cn #远程redis  默认使用本地redis
    password: Yu1998cxl
  application:
    name: activity-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
mybatis:
  type-aliases-package: com.ucpeo.activity.bean
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
#    com.ucpeo.activity.dao : debug
    com.ucpeo.activity.dao.ActDao : debug
