server:
  port: 9090
spring:
#  thymeleaf:
#    cache: false
#    suffix: .html
#    prefix:  classpath:/static/
  application:
    name: activity-web
  cloud:
    nacos:
      server-addr: nacos.yuyoyo.cn:8848
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/